server:
  port: 8999

spring:
  application:
    name: gateway-zuul

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/

zuul:
  routes:
      api-a:
        path: /api-a/**
        serviceId: consumer-ribbon

